# Human friendly name to show up in the repo Actions dashboard
name: Run Tests

# Events or triggers that will activate this workflow
on:
  # Push to the main branch
  push:
    branches: [main]
  # Various pull request events that target the main branch
  pull_request:
    branches: [main]

# Define 1 or more batches of terminal commands
jobs:
  # Job ID
  test:

    # The OS that the job will run on
    # Ubuntu, MacOS, Windows
    runs-on: ubuntu-latest

    # Individual command to run one after the other
    # within the job
    steps:

      # Copying the repo contents into the job runner
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Install NodeJS into the job runner for NPM commands
      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 'latest'
      
      # Prepare the runner workspace with dependencies
      - name: Install dependencies
        run: npm install
      
      # Run our specific test command
      - name: Run tests
        run: npm test
            
